disable header preventing opening links to self
PrivateBin/docker-nginx-fpm-alpine pull request #108
Opened 2022-07-31 06:50 UTC by elrido

fixes #959

2022-07-31 07:08 UTC, rugk requested changes

2022-07-31 07:08 UTC, rugk commented on etc/nginx/http.d/site.conf
> +        # See issue #959 for details.
```suggestion
        # See issue #109 for details.
```

2022-08-01 21:16 UTC, rugk approved these changes

2022-08-02 18:02 UTC, merged

2022-08-02 18:02 UTC, elrido commented
Thank you!